config/routes.rb
Rails.application.routes.draw do
  root "feed#show"

  get "sign_up", to: "users#new"
  post "sign_up", to: "users#create"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resource :profile, only: [:show, :update], controller: "users"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/app_session.rb
class AppSession < ApplicationRecord
  belongs_to :user

  has_secure_password :token, validations: false

  before_create {
    self.token = self.class.generate_unique_secure_token
  }

  def to_h
    {
      user_id: user.id,
      app_session: id,
      token: self.token
    }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user, :app_session, :organization
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :organization
end

app/models/organization.rb
class Organization < ApplicationRecord
	has_many :memberships, dependent: :destroy
	has_many :members, through: :memberships, source: :user

end

app/models/user.rb
class User < ApplicationRecord
  include Authentication

  validates :name,
    on: [:create],
    presence: true
  validates :email,
    on: [:create],
    format: {with: URI::MailTo::EMAIL_REGEXP},
    uniqueness: true

  has_many :memberships, dependent: :destroy
  has_many :organizations, through: :memberships

  before_validation :strip_extraneous_spaces

  private

  def strip_extraneous_spaces
    self.name = self.name&.strip
    self.email = self.email&.strip
  end
end

app/models/user/authentication.rb
module User::Authentication
  extend ActiveSupport::Concern

  included do
    has_secure_password
    validates :password, 
      on: [:create, :password_change],
      presence: true,
      length: {minimum: 8, maximum: ActiveModel::SecurePassword::MAX_PASSWORD_LENGTH_ALLOWED}
    validates :password, 
      on: [:create, :password_change],
      confirmation: {case_sensitive: true}

    has_many :app_sessions
  end

  class_methods do
    def create_app_session(email:, password:)
      return nil unless user = User.find_by(email: email.downcase)

      user.app_sessions.create if user.authenticate(password)
    end
  end

  def authenticate_app_session(app_session_id, token)
    app_sessions.find(app_session_id).authenticate_token(token)
  rescue ActiveRecord::RecordNotFound
    nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authenticate

  helper_method :turbo_frame_request?
  helper_method :turbo_native_app?
end

app/controllers/concerns/authenticate.rb
module Authenticate
  extend ActiveSupport::Concern

  included do
    before_action :authenticate
    before_action :require_login, unless: :logged_in?

    helper_method :logged_in?
  end

  class_methods do
    def skip_authentication(**options)
      skip_before_action :authenticate, options
      skip_before_action :require_login, options
    end

    def allow_unauthenticated(**options)
      skip_before_action :require_login, options
    end
  end

  protected

  def logged_in?
    Current.user.present?
  end

  def log_in(app_session)
    cookies.encrypted.permanent[:app_session] = {value: app_session.to_h}
  end

  def log_out
    Current.app_session&.destroy
  end

  private

  def require_login
    flash.now[:notice] = t("login_required")
    render "sessions/new", status: :unauthorized
  end

  def authenticate
    Current.app_session = authenticate_using_cookie
    Current.user = Current.app_session&.user
  end

  def authenticate_using_cookie
    app_session = cookies.encrypted[:app_session]
    authenticate_using app_session&.with_indifferent_access
  end

  def authenticate_using(data)
    data => {user_id:, app_session:, token:}

    user = User.find(user_id)
    user.authenticate_app_session(app_session, token)
  rescue NoMatchingPatternError, ActiveRecord::RecordNotFound
    nil
  end
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  allow_unauthenticated

  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_authentication only: [:new, :create]

  def new
  end

  def create
    @app_session = User.create_app_session(
      email: login_params[:email],
      password: login_params[:password]
    )

    if @app_session
      log_in(@app_session)

      flash[:success] = t(".success")
      redirect_to root_path, status: :see_other
    else
      flash.now[:danger] = t(".incorrect_details")
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    log_out

    flash[:success] = t(".success")
    redirect_to root_path, status: :see_other
  end

  private

  def login_params
    @login_params ||= params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_authentication only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      @organization = Organization.create(members: [@user])
      @app_session = @user.app_sessions.create
      log_in(@app_session)

      redirect_to root_path, status: :see_other, flash: {success: t(".welcome", name: @user.name)}
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @user = Current.user
  end

  def update
    @user = Current.user

    if @user.update(update_params)
      flash[:success] = t(".success")
      redirect_to profile_path, status: :see_other
    else
      render :show, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def update_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    return t("piazza") unless content_for?(:title)
    return content_for(:title) if turbo_native_app?

    "#{content_for(:title)} | #{t("piazza")}"
  end
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feed/show.html.erb
<h1>Feed#show</h1>
<p>Find me in app/views/feed/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" unless turbo_native_app? %>
    <%= render "shared/flashes"%>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_flashes.html.erb
<div class="container is-fluid" data-turbo-cache="false">
	<% flash.each do |level, message| %>
		<%= tag.div class: "notification is-#{level} is-light has-text-centered mt-4" do %>
			<%= message %>
		<% end %>
	<% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar is-link" data-controller="navbar">
	<div class="navbar-brand">
		<%= link_to root_path, class: "navbar-item" do %>
			<strong class="is-size-3">Piazza</strong>
		<% end %>

		<a role="button" class="navbar-burger" data-navbar-target="burger" data-action="navbar#toggle">
			<span></span>
			<span></span>
			<span></span>
		</a>
	</div>

	<navbar-menu class="navbar-menu" data-navbar-target="menu">
		<div class="navbar-start">
			<%= link_to t(".create_ad"), "#", class: "navbar-item" %>
			<%= link_to t(".messages"), "#", class: "navbar-item" if logged_in? %>
		</div>

		<div class="navbar-end">
			<%= tag.div class: "navbar-item has-dropdown is-hoverable mr-4" do%>
				<%= link_to Current.user.name, 
					profile_path,
					id: "current_user_name",
					class: "navbar-link" %>

				<div class="navbar-dropdown is-right">
					<%= link_to t(".profile"), profile_path, class: "navbar-item" %>
					<%= link_to t(".my_ads"), "#", class: "navbar-item" %>
					<%= link_to t(".saved_ads"), "#", class: "navbar-item" %>
					<hr class="navbar-divider">
					<%= link_to t(".logout"), logout_path, method: :delete, class: "navbar-item", data: {turbo_method: :delete} %>
			<% end if logged_in? %>

			<%= tag.div class: "navbar-item" do %>
				<div class="buttons">
					<%= link_to t(".sign_up"), sign_up_path, class: "button is-primary" %>
					<%= link_to t(".login"), login_path, class: "button is-light" %>
				</div>
			<% end unless logged_in? %>
		</div>
	</navbar-menu>
</nav>

app/views/users/new.html.erb
<% content_for :title, t(".title") %>

<layout-columns class="columns is-centered">
	<layout-columns class="column box is-5 mt-6 p-5 m-4">
		<h1 class="title has-test-centered">
			<%= t(".title") %>
		</h1>

		<%= form_with( model: @user, url: sign_up_path, class: "is-flex is-flex-direction-column") do |form| %>
			<div class="block">
				<%= form.label :name, class: "label" %>
				<%= form.text_field :name, class: "input" %>
			</div>

			<div class="block">
				<%= form.label :email, class: "label" %>
				<%= form.email_field :email, class: "input" %>
			</div>

			<div class="block">
				<%= form.label :password, class: "label" %>
				<%= form.password_field :password, class: "input" %>
			</div>

			<div class="block">
				<%= form.label :password_confirmation, class: "label" %>
				<%= form.password_field :password_confirmation, class: "input" %>
			</div>

			<%= form.submit t(".sign_up"), class: "button is-primary is-large is-align-self-flex-end mb-3 mt-3" %>

			<%= tag.p class: "has-text-centered" do %>
				<%= t(".login_message") %>
				<%= link_to t(".login"), login_path %>
			<% end if turbo_native_app? %>
		<% end %>
	</layout-columns>
</layout-columns>

app/views/users/show.html.erb
<% content_for :title, Current.user.name %>

<%= turbo_frame_tag :user_details do %>
  <layout-columns class="columns is-centered">
  	<layout-column class="column box is-5 mt-6 p-5 m-4">
			<h1 class="title has-text-centered">
				<%= t(".your_details") %>
			</h1>
			<%= form_with(
				model: @user,
				url: profile_path,
				method: :patch,
				class: "is-flex is-flex-direction-column"
				) do |form| %>
					<div class="block">
						<%= form.label :name, class: "label" %>
						<%= form.text_field :name, class: "input" %>
					</div>
					<div class="block">
						<%= form.label :email, class: "label" %>
						<%= form.email_field :email, class: "input" %>
					</div>

					<%= form.submit t(".save_profile"), class: "button is-primary is-align-self-flex-end mb-3 mt-3" %>

					<%= render "shared/flashes" if turbo_frame_request? %>
					<%= turbo_stream.update :current_user_name do %>
						<%= Current.user.name %>
					<% end %>
			<% end %>
		</layout-column>
	</layout-columns>
<% end %>

<%= turbo_frame_tag :change_password do %>
  <layout-columns class="columns is-centered">
  	<layout-column class="column box is-5 mt-6 p-5 m-4">
  		<h1 class="title has-text-centered">
  			<%= t(".change_password") %>
  		</h1>
			<%= form_with(
				model: @user,
				url: "#",
				class: "is-flex is-flex-direction-column"
				) do |form| %>
					<div class="block">
						<%= form.label :current_password, value: t(".current_password"), class: "label" %>
						<%= form.password_field :current_password, class: "input" %>
					</div>
					<div class="block">
						<%= form.label :password, value: t(".new_password"), class: "label" %>
						<%= form.password_field :password, class: "input" %>
					</div>

					<%= form.submit t(".change_password_button"), class: "button is-primary is-align-self-flex-end mb-3 mt-3" %>

					<%= render "shared/flashes" if turbo_frame_request? %>
			<% end %>
		</layout-column>
	</layout-columns>
<% end %>